spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/cme;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

liquibase:
  change-log: classpath:/changelog/db.changelog-master.xml

security:
  basic:
    enabled: false
